config/routes.rb
scope '/projects/:project_id' do
  match '/change_metric' => 'bsc_metrics#change_metric', :via => [:get, :post, :put, :patch]
  match '/management' => 'bsc_management#index', :via => [:get, :post, :put, :patch]
  match '/management/delete' => 'bsc_management#destroy', :via => :delete
  get '/metrics' => 'bsc_metrics#index'
  match '/checkpoints/new_without_annualization', :to => 'bsc_checkpoints#new_without_annualization', :via => [:get, :post, :put, :patch]
  match '/checkpoints/create_without_annualization', :to => 'bsc_checkpoints#create_without_annualization', :via => [:get, :post, :put, :patch]
  resources :checkpoints, :controller => 'bsc_checkpoints' do
    collection do
      match '/preview', :to => 'previews#checkpoint', :via => [:get, :post, :put, :patch]
    end
  end
end

match '/settings/show_tracker_custom_fields' => 'settings#show_tracker_custom_fields', :via => [:get, :post]
match '/settings/show_tracker_statuses' => 'settings#show_tracker_statuses', :via => [:get, :post]
match 'projects/:id/setting_bsc_manage_dates' => 'projects#setting_bsc_manage_dates', via: [:post, :put], :as => 'projects_setting_bsc_manage_dates'

app/controllers/bsc_checkpoints_controller.rb
class BscCheckpointsController < ApplicationController
	before_filter :find_project_by_project_id, :authorize
  before_filter :get_profiles, :only => [:new, :new_without_annualization, :edit, :show]
  before_filter :get_hourly_cost, :only => [:new, :edit, :update, :create]
  before_filter :find_checkpoint, :only => [:show, :edit, :update, :destroy]
  before_filter :has_bsc_project_info
	
  menu_item :bsc
	helper :bsc

  def index
    @limit = per_page_option
    @count = BscCheckpoint.where('project_id = ?', @project).count
    @pages = Paginator.new @count, @limit, params['page']
    @offset ||= @pages.current.offset
    @sort = sort_column
    @order = sort_direction
    @checkpoints = BscCheckpoint.where(project_id: @project).
                                    	order([[@sort, @order].join(' '),['created_at', @order].join(' ')].join(',')).
                                     	offset(@offset).
                                     	limit(@limit).
                                     	includes(:bsc_checkpoint_efforts)       	
  end

  def new
    @checkpoint = BscCheckpoint.new @project

    if @project.first_checkpoint.blank?
      @first_checkpoint = true
      @checkpoint.base_line = true
      @checkpoint.scheduled_finish_date = @project.bsc_info.scheduled_finish_date
    end
    
    @profiles.each do |profile|
      @checkpoint.bsc_checkpoint_efforts.build :hr_profile_id => profile.id
    end

    @last_checkpoint = @project.last_checkpoint
  end

  def new_without_annualization
    @checkpoint = BscCheckpoint.new @project

    if @project.first_checkpoint.blank?
      @first_checkpoint = true
      @checkpoint.base_line = true
      @checkpoint.scheduled_finish_date = @project.bsc_info.scheduled_finish_date
    end
    
    @profiles.each do |profile|
      @checkpoint.bsc_checkpoint_efforts.build :hr_profile_id => profile.id
    end

    @last_checkpoint = @project.last_checkpoint
  end

  def create
    @checkpoint = BscCheckpoint.new checkpoint_params
    @checkpoint.project = @project
    @checkpoint.author = User.current
    if @checkpoint.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => :index
    else
      get_profiles
      render :action => 'new'
    end
  end

  def create_without_annualization
    efforts = []
    checkpoint_params['bsc_checkpoint_efforts_attributes'].each do |eff|
      scheduled_effort_day = (eff[:scheduled_effort].to_f / (checkpoint_params[:scheduled_finish_date].to_date - @project.bsc_start_date + 1)).to_f
      (@project.bsc_start_date.year..checkpoint_params[:scheduled_finish_date].to_date.year).each do |year|
        effort = BscCheckpointEffort.new(eff)
        effort[:scheduled_effort] = scheduled_effort_day * ([checkpoint_params[:scheduled_finish_date].to_date, "31-12-#{year}".to_date].min - [@project.bsc_start_date, "01-01-#{year}".to_date].max + 1)
        effort[:year] = year
        efforts << effort
      end
    end

    params[:checkpoint]['bsc_checkpoint_efforts_attributes'] = efforts.map(&:attributes)

    @checkpoint = BscCheckpoint.new checkpoint_params
    @checkpoint.project = @project
    @checkpoint.author = User.current

    if @checkpoint.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => :index
    else
      get_profiles
      render :action => 'new_without_annualization'
    end
  end

  def show
    @journals = @checkpoint.journals.includes(:user, :details).order("#{Journal.table_name}.created_on ASC")
    @journals.each_with_index {|j,i| j.indice = i+1}
    @journals = @journals.reverse if User.current.wants_comments_in_reverse_order?
  end

  def edit
    @journal = @checkpoint.current_journal
    @first_checkpoint = (@project.first_checkpoint == @checkpoint)
    @last_checkpoint = BscCheckpoint.where("project_id = ? AND checkpoint_date <= ? AND id != ?", @project.id, @checkpoint.checkpoint_date, @checkpoint.id).order("checkpoint_date DESC, created_at DESC").first
  end

  def update
    @checkpoint.init_journal(User.current, params[:notes])
    @checkpoint.attributes = checkpoint_params #params[:checkpoint]

    if @checkpoint.save
      flash[:notice] = l(:notice_successful_update)
      redirect_back_or_default({:action => 'show', :id => @checkpoint})
    else
      get_profiles
      @journal = @checkpoint.current_journal
      render :action => 'edit'
    end
  end

  def destroy
    @checkpoint.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_back_or_default(:action => 'index', :project_id => @project)
  end

  private

  def find_checkpoint
    @checkpoint = BscCheckpoint.includes(:bsc_checkpoint_efforts).find(params[:id])
    unless @checkpoint.project_id == @project.id
      deny_access
      return
    end
  end

  def sort_column
    BscCheckpoint.column_names.include?(params[:sort]) ? params[:sort] : "checkpoint_date"
  end

  def sort_direction
    %w[asc desc].include?(params[:order]) ? params[:order] : "desc"
  end

  def get_profiles
    @profiles = BSC::Integration.get_profiles(@project.bsc_start_date)
  end

  def checkpoint_params
    if !User.current.allowed_to?(:bsc_manage_dates, @project) and @project.bsc_manage_dates
      # params.require(:checkpoint).permit(:project_id, :author_id, :description, :checkpoint_date, :held_qa_meetings, :base_line, :achievement_percentage, :title, bsc_checkpoint_efforts_attributes: [:id, :hr_profile_id, :scheduled_effort, :number, :year])
      last_checkpoint = @project.real_last_checkpoint
      if last_checkpoint.present?
        params[:scheduled_finish_date] = last_checkpoint.scheduled_finish_date
        params[:target_expenses] = last_checkpoint.target_expenses
        params[:target_incomes] = last_checkpoint.target_incomes
      else
        params[:scheduled_finish_date] = @project.bsc_info.scheduled_finish_date
        params[:target_expenses] = ""
        params[:target_incomes] = ""
      end
    end
    params.require(:checkpoint).permit(:project_id, :author_id, :description, :checkpoint_date, :scheduled_finish_date, :held_qa_meetings, :base_line, :target_expenses, :target_incomes, :achievement_percentage, :title, bsc_checkpoint_efforts_attributes: [:id, :hr_profile_id, :scheduled_effort, :number, :year])
  end

  def has_bsc_project_info
    unless @project.bsc_info.present?
      deny_access
      return
    end
  end

  def get_hourly_cost
    @hourly_cost = Hash.new(Hash.new(0.0))
    (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year|
      @hourly_cost[year] = BSC::Integration.get_hourly_cost_array(year)
    end
  end
end

app/helpers/bsc_checkpoints_helper.rb
module BscCheckpointsHelper
	# Returns a link which sorts by the named column.
  #
  # - column is the name of an attribute in the sorted record collection.
  # - the optional caption explicitly specifies the displayed link text.
  # - 2 CSS classes reflect the state of the link: sort and asc or desc
  #
  def sort_link(column, caption, default_order)
    css, order = nil, default_order

    if @sort == column
      if @order == 'asc'
        css = 'sort asc'
        order = 'desc'
      else
        css = 'sort desc'
        order = 'asc'
      end
    end
    caption = column.to_s.humanize unless caption

    sort_options = { :sort => column.to_s, :order => order }
    url_options = params.merge(sort_options)

    # Add project_id to url_options
    url_options = url_options.merge(:project_id => params[:project_id]) if params.has_key?(:project_id)

    link_to_content_update(caption, url_options, :class => css)
  end

  # Returns a table header <th> tag with a sort link for the named column
  # attribute.
  #
  # Options:
  #   :caption     The displayed link name (defaults to titleized column name).
  #   :title       The tag's 'title' attribute (defaults to 'Sort by :caption').
  #
  # Other options hash entries generate additional table header tag attributes.
  #
  # Example:
  #
  #   <%= sort_header_tag('id', :title => 'Sort by contact ID', :width => 40) %>
  #
  def sort_header_tag(column, options = {})
    caption = options.delete(:caption) || column.to_s.humanize
    default_order = options.delete(:default_order) || 'asc'
    options[:title] = l(:label_sort_by, "\"#{caption}\"") unless options[:title]
    content_tag('th', sort_link(column, caption, default_order), options)
  end

  def render_notes(model, journal, options={})
    content = ''
    editable = User.current.logged? && (User.current.allowed_to?(:edit_issue_notes, model.project) || (journal.user == User.current && User.current.allowed_to?(:edit_own_issue_notes, model.project)))
    links = []
    if !journal.notes.blank?
      links << link_to_in_place_notes_editor(image_tag('edit.png'), "journal-#{journal.id}-notes", 
      																					{ :controller => 'journals', :action => 'edit', :id => journal, :format => 'js' },
                                                :title => l(:button_edit)) if editable
    end
    content << content_tag('div', links.join(' ').html_safe, :class => 'contextual') unless links.empty?
    content << textilizable(journal, :notes)
    css_classes = "wiki"
    css_classes << " editable" if editable
    content_tag('div', content.html_safe, :id => "journal-#{journal.id}-notes", :class => css_classes).html_safe
  end

  # (copied from journals_helper)
  def link_to_in_place_notes_editor(text, field_id, url, options={})
    onclick = "$.ajax({url: '#{url_for(url)}', type: 'get'}); return false;"
    link_to text, '#', options.merge(:onclick => onclick)
  end

  # Show differences in notes
  # Returns the textual representation of a single journal detail (copied from issues_helper)
  def show_detail(detail, no_html=false, options={})
    multiple = false
    show_diff = false

    case detail.property
    when 'attr'
      field = detail.prop_key.to_s.gsub(/\_id$/, "")
      label = l(("field_" + field).to_sym)
      case detail.prop_key
      when 'scheduled_profile_effort'
        profiles = Hash.new('Unknwon').merge(HrProfile.all.map{|p| [p.id, p.name]}.to_h)
        detail.value = eval(detail.value).map{|k, v| [profiles[k], v] }.to_h
      when 'due_date', 'start_date'
        value = format_date(detail.value.to_date) if detail.value
        old_value = format_date(detail.old_value.to_date) if detail.old_value

      when 'project_id', 'status_id', 'tracker_id', 'assigned_to_id',
            'priority_id', 'category_id', 'fixed_version_id'
        value = find_name_by_reflection(field, detail.value)
        old_value = find_name_by_reflection(field, detail.old_value)

      when 'estimated_hours'
        value = "%0.02f" % detail.value.to_f unless detail.value.blank?
        old_value = "%0.02f" % detail.old_value.to_f unless detail.old_value.blank?

      when 'parent_id'
        label = l(:field_parent_issue)
        value = "##{detail.value}" unless detail.value.blank?
        old_value = "##{detail.old_value}" unless detail.old_value.blank?

      when 'is_private'
        value = l(detail.value == "0" ? :general_text_No : :general_text_Yes) unless detail.value.blank?
        old_value = l(detail.old_value == "0" ? :general_text_No : :general_text_Yes) unless detail.old_value.blank?

      when 'description'
        show_diff = true
      end
    when 'cf'
      custom_field = detail.custom_field
      if custom_field
        label = custom_field.name
        if custom_field.format.class.change_as_diff
          show_diff = true
        else
          multiple = custom_field.multiple?
          value = format_value(detail.value, custom_field) if detail.value
          old_value = format_value(detail.old_value, custom_field) if detail.old_value
        end
      end
    when 'attachment'
      label = l(:label_attachment)
    when 'relation'
      if detail.value && !detail.old_value
        rel_issue = Issue.visible.find_by_id(detail.value)
        value = rel_issue.nil? ? "#{l(:label_issue)} ##{detail.value}" :
                  (no_html ? rel_issue : link_to_issue(rel_issue, :only_path => options[:only_path]))
      elsif detail.old_value && !detail.value
        rel_issue = Issue.visible.find_by_id(detail.old_value)
        old_value = rel_issue.nil? ? "#{l(:label_issue)} ##{detail.old_value}" :
                          (no_html ? rel_issue : link_to_issue(rel_issue, :only_path => options[:only_path]))
      end
      relation_type = IssueRelation::TYPES[detail.prop_key]
      label = l(relation_type[:name]) if relation_type
    end
    call_hook(:helper_issues_show_detail_after_setting,
              {:detail => detail, :label => label, :value => value, :old_value => old_value })

    label ||= detail.prop_key
    value ||= detail.value
    old_value ||= detail.old_value

    unless no_html
      label = content_tag('strong', label)
      old_value = content_tag("i", h(old_value)) if detail.old_value
      if detail.old_value && detail.value.blank? && detail.property != 'relation'
        old_value = content_tag("del", old_value)
      end
      if detail.property == 'attachment' && value.present? &&
          atta = detail.journal.journalized.attachments.detect {|a| a.id == detail.prop_key.to_i}
        # Link to the attachment if it has not been removed
        value = link_to_attachment(atta, :download => true, :only_path => options[:only_path])
        if options[:only_path] != false && atta.is_text?
          value += link_to(
                       image_tag('magnifier.png'),
                       :controller => 'attachments', :action => 'show',
                       :id => atta, :filename => atta.filename
                     )
        end
      else
        value = content_tag("i", h(value)) if value
      end
    end

    if show_diff
      s = l(:text_journal_changed_no_detail, :label => label)
      unless no_html
        diff_link = link_to 'diff',
          {:controller => 'journals', :action => 'diff', :id => detail.journal_id,
           :detail_id => detail.id, :only_path => options[:only_path]},
          :title => l(:label_view_diff)
        s << " (#{ diff_link })"
      end
      s.html_safe
    elsif detail.value.present?
      case detail.property
      when 'attr', 'cf'
        if detail.old_value.present?
          l(:text_journal_changed, :label => label, :old => old_value, :new => value).html_safe
        elsif multiple
          l(:text_journal_added, :label => label, :value => value).html_safe
        else
          l(:text_journal_set_to, :label => label, :value => value).html_safe
        end
      when 'attachment', 'relation'
        l(:text_journal_added, :label => label, :value => value).html_safe
      end
    else
      l(:text_journal_deleted, :label => label, :old => old_value).html_safe
    end
  end

  def render_checkpoint_effort_info(effort, number)
    (number > 0) ? 
      effort.to_s+" ("+number.to_s+" perfiles)" :
      effort
  end

end

app/views/bsc_checkpoints/_edit.html.erb
<%= labelled_form_for :checkpoint, @checkpoint,
                             :url => {:action => 'update', :id => @checkpoint},
                             :html => {:id => 'checkpoint-form',
                                       :class => nil,
                                       :method => :put} do |f| %>
    <%= error_messages_for 'checkpoint' %>
    <div class="box">
      <fieldset class="tabular">
        <legend><%= l(:label_change_properties) %></legend>
        <%= render :partial => 'form', :locals => {:f => f} %>
      </fieldset>

    <fieldset><legend><%= l(:field_notes) %></legend>
    <%= text_area_tag 'notes', @notes, :cols => 60, :rows => 10, :class => 'wiki-edit' %>
    <%= wikitoolbar_for 'notes' %>

    </fieldset>
    </div>

    <%= submit_tag l(:button_submit) %>
    <%= preview_link preview_checkpoints_path(:project_id => @project, :id => @checkpoint), 'checkpoint-form' %>
<% end %>

<div id="preview" class="wiki"></div>

app/views/bsc_checkpoints/_efforts_table.html.erb
<table id="checkpoint_efforts_form">
  <tr>
    <th></th>
    <% (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year| %>
    <th><%=year%></th>
    <% end %>
    <th class="total"><%=l(:"bsc.label_total")%> (€)</th>
    <th class="total"><%=l(:"bsc.label_previous")%> (€)</th>
    <th class="total"><%=l(:"bsc.label_difference")%> (€)</th>
  </tr>
  <% @profiles.each do |profile| %>
  <tr>
    <th><%=profile.name%></th>
    <% (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year| %>
    <td class="checkpoint_cell">
      <%= render :partial => 'year', :locals => {:checkpoint => @checkpoint, :profile => profile, :year => year} %>
    </td>
    <% end %>
    <!-- Total column -->
    <td class="checkpoint_cell total" data-total="profile" data-profile="<%=profile.id%>"></td>
    <!-- Total previous column -->
    <td class="checkpoint_cell total" data-total="previous" data-profile="<%=profile.id%>">
      <% if @last_checkpoint.present? %>
      <%=@last_checkpoint.scheduled_profile_effort_cost(profile.id).values.sum.round(2)%>
      <% else %>
      0.00
      <% end %>
    </td>
    <!-- Difference column -->
    <td class="checkpoint_cell total" data-total="diff" data-profile="<%=profile.id%>"></td>
  </tr>
  <% end %>
  <!-- Total row -->
  <tr>
    <th class="checkpoint_cell total"><b><%=l(:"bsc.label_total")%> (€)</b></th>
    <% (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year| %>
      <td class="checkpoint_cell total" data-total="year" data-year="<%=year%>">
    <% end %>
    <td class="checkpoint_cell total_total" data-total="total"></td>
    <td class="checkpoint_cell total_total" data-total="total_previous">
      <% if @last_checkpoint.present? %>
      <%=@last_checkpoint.scheduled_effort_cost.round(2)%>
      <% else %>
      0.00
      <% end %>
    </td>
    <td class="checkpoint_cell total_total" data-total="total_diff"></td>
  </tr>
  <!-- Total previous row -->
    <th class="checkpoint_cell total"><b><%=l(:"bsc.label_previous")%> (€)</b></th>
    <% (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year| %>
      <td class="checkpoint_cell total" data-total="previous" data-year="<%=year%>">
      <% if @last_checkpoint.present? %>
      <%=@last_checkpoint.scheduled_profile_effort_year_cost(year).values.sum.round(2)%>
      <% else %>
      0.00
      <% end %>
      </td>
    <% end %>
    <td></td>
    <td></td>
    <td></td>
  <tr>
  </tr>
  <!-- Difference row -->
  <tr>
    <th class="checkpoint_cell total"><b><%=l(:"bsc.label_difference")%> (€)</b></th>
    <% (@project.bsc_start_date.year..@project.bsc_end_date.year).each do |year| %>
    <td class="checkpoint_cell total" data-total="diff" data-year="<%=year%>"></td>
    <% end %>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/bsc_checkpoints/_history.html.erb
<% reply_links = false #authorize_for('journals', 'edit') %>
<% for journal in journals %>
  <div id="change-<%= journal.id %>" class="<%= journal.css_classes %>">
    <div id="note-<%= journal.indice %>">
    <h4><a href="#note-<%= journal.indice %>" class="journal-link">#<%= journal.indice %></a>
    <%= avatar(journal.user, :size => "24") %>
    <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
    <%= content_tag('span', l(:field_is_private), :class => 'private') if journal.private_notes? %></h4>

    <% if journal.details.any? %>
    <ul class="details">
      <% for detail in journal.details %>
          <li><%= show_detail(detail).html_safe %></li>
        <% end %>
    </ul>
    <% if Setting.thumbnails_enabled? && (thumbnail_attachments = journal_thumbnail_attachments(journal)).any? %>
      <div class="thumbnails">
        <% thumbnail_attachments.each do |attachment| %>
          <div><%= thumbnail_tag(attachment) %></div>
        <% end %>
      </div>
    <% end %>
    <% end %>
    <%= render_notes(checkpoint, journal, :reply_links => reply_links) unless journal.notes.blank? %>
    </div>
  </div>
<% end %>

app/views/bsc_checkpoints/_year.html.erb
<%= hidden_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][id]", checkpoint.scheduled_profile_effort_id(profile.id)[year] %>
<%= hidden_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][hr_profile_id]", profile.id %>
<%= hidden_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][year]", year %>
<%= text_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][scheduled_effort]", checkpoint.scheduled_profile_effort(profile.id)[year], :size => 5, :data => {:year => year, :profile => profile.id} %>

app/views/bsc_checkpoints/edit.html.erb
<h2><%=l :"bsc.label_checkpoints" %></h2>
<%= render_project_bsc_tab('checkpoints') %>

<h3><%= @checkpoint.checkpoint_date %></h3>

<%= render :partial => 'edit' %>

app/views/bsc_checkpoints/index.html.erb
<%= render_project_bsc_tab('checkpoints') %>

<h2><%=l(:"bsc.label_checkpoints")%></h2>

<% if @checkpoints.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <div class="autoscroll">
  <table class="list issues">
    <thead>
      <tr>
        <%= sort_header_tag('checkpoint_date', :caption => t(:label_date), :default_order => 'desc') %>
        <%= content_tag('th', t(:"bsc.label_title")) %>
        <%= content_tag('th', t(:"bsc.label_effort")) %>
        <%= content_tag('th', t(:field_scheduled_finish_date)) %>
        <%= content_tag('th', t(:field_held_qa_meetings)) %>
        <%= content_tag('th', t(:field_target_incomes)) %>
        <%= content_tag('th', t(:field_target_expenses)) %>
        <%= content_tag('th', t(:field_achievement_percentage)) %>
        <%= content_tag('th', t(:field_base_line)) %>
        <%= content_tag('th', t(:field_author)) %>
      </tr>
    </thead>
    <tbody>
    <% @checkpoints.each do |checkpoint| -%>
      <tr id="checkpoint-<%= checkpoint.id %>" class="<%= cycle('odd', 'even') %> issue">
        <td><%= link_to checkpoint.checkpoint_date, checkpoint_path(@project, checkpoint) %></td>
        <td><%= link_to (checkpoint.title.present? ? checkpoint.title : '-'), checkpoint_path(@project, checkpoint) %></td>
        <%= content_tag 'td', hours(checkpoint.bsc_checkpoint_efforts.reduce(0.0){ |sum, effort| sum += effort.scheduled_effort }) %>
        <%= content_tag 'td', checkpoint.scheduled_finish_date %>
        <%= content_tag 'td', checkpoint.held_qa_meetings %>
        <%= content_tag 'td', checkpoint.target_incomes.round(2) %>
        <%= content_tag 'td', checkpoint.target_expenses.round(2) %>
        <%= content_tag 'td', checkpoint.achievement_percentage.to_s+'%' %>
        <%= content_tag 'td', if checkpoint.base_line 
                                image_tag 'toggle_check.png' 
                              end
                          %>
        <%= content_tag 'td', checkpoint.author %>
      </tr>
    <% end -%>
    </tbody>
  </table>
  </div>
  <p class="pagination splitcontentleft"><%= pagination_links_full @pages, @count %></p>
<% end %>

<div class="contextual">
  <%= link_to_if_authorized l(:label_new), {:action => 'new'}, :class => 'icon icon-add' %>
  <%= link_to_if_authorized l(:"bsc.label_new_without_annualization"), {:action => 'new_without_annualization'}, :class => 'icon icon-add' if @checkpoints.empty? %>
</div>

app/views/bsc_checkpoints/new.html.erb
<h2><%=l(:'bsc.label_new_checkpoint')%></h2>
<%= render_project_bsc_tab('checkpoints') %>

<%= labelled_form_for :checkpoint, @checkpoint,
                          :url => { :controller => 'bsc_checkpoints', :action => 'create', :project_id => @project },
                          :html => {:id => 'checkpoint-form', :class => 'tabular'} do |f| %>

  <%= error_messages_for 'checkpoint' %>

  <div class="box">
    <%= render :partial => 'form', :locals => {:f => f} %>
  </div>

  <%= submit_tag(l(:button_create)) %>
  <%= preview_link preview_checkpoints_path(:project_id => @project), 'checkpoint-form' %>
<% end %>
<div id="preview" class="wiki"></div>

app/views/bsc_checkpoints/new_without_annualization.html.erb
<h2><%=l(:'bsc.label_new_checkpoint')%></h2>
<%= render_project_bsc_tab('checkpoints') %>

<%= labelled_form_for :checkpoint, @checkpoint,
                          :url => { :controller => 'bsc_checkpoints', :action => 'create_without_annualization', :project_id => @project },
                          :html => {:id => 'checkpoint-form', :class => 'tabular'} do |f| %>

  <%= error_messages_for 'checkpoint' %>

  <div class="box">
    <div class="splitcontentleft">
      <p><%= f.text_field :checkpoint_date, :size => 10, :required => true %><%= calendar_for('checkpoint_checkpoint_date') %></p>
      <p><%= f.text_field :scheduled_finish_date, :size => 10, :required => true %><%= calendar_for('checkpoint_scheduled_finish_date') %></p>
      <p><%= f.text_field :held_qa_meetings, :size => 10, :required => true %></p>
      <p><%= f.check_box :base_line, :disabled => @first_checkpoint %></p>
    </div>
    <div class="splitcontentright">
      <p><%= f.text_field :target_incomes, :size => 10, :required => true %></p>
      <p><%= f.text_field :target_expenses, :size => 10, :required => true %></p>
      <p><%= f.text_field :achievement_percentage, :size => 3, :required => true %> %</p>
    </div>
    <div style="clear:both;"></div>
    <% if @profiles.length > 0
         profiles = @profiles.dup
         profiles.push nil if profiles.length.odd?
         columns = profiles.each_slice(2).to_a.transpose
         columns[-1].pop if columns[-1][-1].nil? %>
      <% ["splitcontentleft", "splitcontentright"].each_with_index do |css_class, i| %>
        <div class="<%= css_class %>">
          <% columns[i].each do |profile| %>
            <p>
              <%= label_tag "checkpoint_scheduled_profile_effort_#{profile.name}",
                            l(:"bsc.label_scheduled_profile_effort", :profile => profile.name).html_safe + '<span class="required"> *</span>'.html_safe %>
              <%= hidden_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][id]" %>
              <%= hidden_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][hr_profile_id]", profile.id %>
              <%= text_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][scheduled_effort]", 0.00, :size => 10 %>
              <%= l(:"bsc.label_profile_plural") %>
              <%= text_field_tag "checkpoint[bsc_checkpoint_efforts_attributes][][number]", 0.0, :size => 1 %>
            </p>
          <% end %>
        </div>
      <% end %>
      <div style="clear:both;"></div>
    <% end %>
    <p><%= f.text_area :description,
                       :cols => 60,
                       :rows => (@checkpoint.description.blank? ? 10 : [[10, @checkpoint.description.length / 50].max, 100].min),
                       :accesskey => accesskey(:edit),
                       :class => 'wiki-edit' %></p>

    <%= wikitoolbar_for 'checkpoint_description' %>
  </div>

  <%= submit_tag(l(:button_create)) %>
  <%= preview_link preview_checkpoints_path(:project_id => @project), 'checkpoint-form' %>
<% end %>
<div id="preview" class="wiki"></div>